root:
    pattern:  /
    defaults: { _controller: InouireMininetBundle:Default:root }
    
home:
    pattern:  /home
    defaults: { _controller: InouireMininetBundle:Default:home }

album:
    pattern:  /album
    defaults: { _controller: InouireMininetBundle:Default:album }
