#main routes
root:
    pattern:  /
    defaults: { _controller: InouireMininetBundle:Default:root }
    
home:
    pattern:  /home
    defaults: { _controller: InouireMininetBundle:Default:home }

album:
    pattern:  /album
    defaults: { _controller: InouireMininetBundle:Default:album }


#routes for actions on posts
new_post:
    pattern:  /post
    defaults: { _controller: InouireMininetBundle:Post:new }

edit_post:
    pattern:  /post/{post_id}
    requirements:
        post_id:  \d+
        _method:  GET
    defaults: { _controller: InouireMininetBundle:Post:edit }   

update_post_content:
    pattern:  /post/{post_id}
    requirements:
        post_id:  \d+
        _method:  UPDATE
    defaults: { _controller: InouireMininetBundle:Post:updateContent }
    
update_post_status:
    pattern:  /post/{post_id}
    requirements:
        post_id:  \d+
        _method:  POST
    defaults: { _controller: InouireMininetBundle:Post:updateStatus }

delete_post:
    pattern:  /post/{post_id}
    requirements:
        post_id:  \d+
        _method:  DELETE
    defaults: { _controller: InouireMininetBundle:Post:delete }
    
#routes for actions on comments
post_comment:
    pattern:  /post/{post_id}/comment
    requirements:
        post_id:  \d+
        _method:  POST
        _format:  json | html
    defaults: { _controller: InouireMininetBundle:Comment:postComment }

delete_comment:
    pattern:  /post/{post_id}/comment/{comment_id}
    requirements:
        post_id:  \d+
        comment_id:  \d+
        _method:  DELETE
        _format:  json | html
    defaults: { _controller: InouireMininetBundle:Comment:deleteComment }
    
    
test:
    pattern:  /test
    defaults: { _controller: InouireMininetBundle:Default:test }
