#main routes
root:
    pattern:  /
    defaults: { _controller: InouireMininetBundle:Default:root }
    
home:
    pattern:  /home
    defaults: { _controller: InouireMininetBundle:Default:home }

album:
    pattern:  /album
    defaults: { _controller: InouireMininetBundle:Default:album }


#routes for actions on posts
view_post:
    pattern:  /post/{post_id}
    requirements:
        post_id:  \d+
        _method:  GET
    defaults: { _controller: InouireMininetBundle:Post:view }
    
new_post:
    pattern:  /post/new
    defaults: { _controller: InouireMininetBundle:Post:new }

edit_post:
    pattern:  /post/{post_id}/edit
    requirements:
        post_id:  \d+
    defaults: { _controller: InouireMininetBundle:Post:edit }   

update_post_content:
    pattern:  /post/{post_id}
    requirements:
        post_id:  \d+
        _method:  POST
        _format:  json
    defaults: { _controller: InouireMininetBundle:Post:update }
    
delete_post:
    pattern:  /post/{post_id}
    requirements:
        post_id:  \d+
        _method:  DELETE
        _format:  json
    defaults: { _controller: InouireMininetBundle:Post:update }
    
#routes for actions on comments
post_comment:
    pattern:  /comment
    requirements:
        _method:  POST
        _format:  json
    defaults: { _controller: InouireMininetBundle:Comment:postComment }

delete_comment:
    pattern:  /comment/{comment_id}
    requirements:
        comment_id:  \d+
        _method:  DELETE
        _format:  json
    defaults: { _controller: InouireMininetBundle:Comment:deleteComment }
    
